import test from "node:test";import assert from "node:assert/strict";import {chmodSync,mkdtempSync,rmSync,writeFileSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {configSchema,loadConfig} from "../src/config.ts";import {authorizeMatrixEvent} from "../src/matrix/matrix-crypto-policy.ts";import {parsePiCommand} from "../src/matrix/matrix-event-router.ts";import {isCommandAuthorized} from "../src/daemon.ts";import {threadRoot,threadMessageContent} from "../src/matrix/conversation-model.ts";
const base={version:1 as const,matrix:{enabled:false},signal:{enabled:false},agents:[{id:"backend",name:"Backend",cwd:"/tmp",mode:"managed" as const}]};
test("configuration loading requires private files and directories",()=>{const dir=mkdtempSync(join(tmpdir(),"pi-ngv2-config-")),file=join(dir,"config.json");try{chmodSync(dir,0o700);writeFileSync(file,JSON.stringify(base),{mode:0o600});assert.equal(loadConfig(file).version,1);chmodSync(file,0o644);assert.throws(()=>loadConfig(file),/0600/);}finally{rmSync(dir,{recursive:true,force:true});}});
test("disabled Signal needs no account",()=>{const parsed=configSchema.parse(base);assert.equal(parsed.signal.enabled,false);assert.equal(parsed.matrix.conversationMode,"thread");assert.equal(configSchema.parse({...base,matrix:{enabled:false,conversationMode:"room"}}).matrix.conversationMode,"room");});
test("Matrix config fails closed when allowlists are absent",()=>{assert.throws(()=>configSchema.parse({...base,matrix:{enabled:true,homeserver:"https://matrix.example",userId:"@bot:example",accessTokenFile:"/tmp/token"}}));});
test("profiles reject arbitrary shape and duplicate ids",()=>{assert.throws(()=>configSchema.parse({...base,agents:[base.agents[0],base.agents[0]]}));});
test("Matrix authorization is fail closed",()=>{const event={transport:"matrix" as const,eventId:"$e",senderId:"@u:x",roomId:"!r:x",threadId:"$e",text:"hi",timestamp:1,encrypted:true,trusted:true};const cfg={botUserId:"@bot:x",allowedUsers:["@u:x"],allowedRooms:["!r:x"],requireEncryption:true,requireVerifiedDevices:true,strictRoomMembership:true};assert.deepEqual(authorizeMatrixEvent(event,{encrypted:true,decrypted:true,deviceTrusted:true,members:["@u:x","@bot:x"]},cfg),{allowed:true});assert.equal(authorizeMatrixEvent({...event,trusted:false},{encrypted:true,decrypted:true,deviceTrusted:false,members:[]},cfg).allowed,false);assert.equal(authorizeMatrixEvent(event,{encrypted:false,decrypted:true,deviceTrusted:true,members:[]},cfg).allowed,false);assert.equal(authorizeMatrixEvent(event,{encrypted:true,decrypted:true,deviceTrusted:true,members:["@evil:x"]},cfg).allowed,false);});
test("privileged commands require an administrator in a control room",()=>{assert.equal(isCommandAuthorized("attach","@admin:x","!control:x",["@admin:x"],["!control:x"]),true);assert.equal(isCommandAuthorized("attach","@user:x","!control:x",["@admin:x"],["!control:x"]),false);assert.equal(isCommandAuthorized("attach","@admin:x","!agent:x",["@admin:x"],["!control:x"]),false);assert.equal(isCommandAuthorized("new","@user:x","!agent:x",[],[]),true);});
test("thread mapping and typed commands",()=>{assert.equal(threadRoot("$reply",{"m.relates_to":{rel_type:"m.thread",event_id:"$root"}}),"$root");assert.equal((threadMessageContent("x","$root")["m.relates_to"] as any).event_id,"$root");assert.deepEqual(parsePiCommand("!pi new backend fix auth"),{kind:"new",agentId:"backend",prompt:"fix auth"});assert.deepEqual(parsePiCommand("!pi new"),{kind:"new",agentId:""});assert.deepEqual(parsePiCommand("/pi status"),{kind:"status"});assert.equal(parsePiCommand("/new"),undefined);});
