import { chmodSync, existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { CollectStrategy, DeviceId, DeviceLists, EncryptionSettings, OlmMachine, RequestType, RoomId, ShieldColor, StoreType, UserId } from "@matrix-org/matrix-sdk-crypto-nodejs";
import { ensurePrivateDirectory } from "../paths.ts";
import { readSecretFile } from "../secrets.ts";
import { threadMessageContent } from "./conversation-model.ts";
export interface MatrixInbound{roomId:string;eventId:string;senderId:string;timestamp:number;content:Record<string,unknown>;trusted:boolean;}
export interface MatrixClientAdapter{start(handler:(event:MatrixInbound)=>Promise<void>):Promise<void>;stop():Promise<void>;onHealth(handler:(healthy:boolean,detail?:string)=>void):()=>void;sendEncrypted(roomId:string,threadId:string|undefined,text:string,transactionId:string,notice?:boolean):Promise<string>;isRoomEncrypted(roomId:string):Promise<boolean>;members(roomId:string):Promise<string[]>;identity():Promise<{userId:string;deviceId:string;fingerprint:string}>;trustReport(roomId:string):Promise<{total:number;trusted:number}>;}
export interface MatrixClientOptions{homeserver:string;userId:string;accessTokenFile:string;storageDir:string;requireVerifiedDevices:boolean;allowedRooms:string[];allowedUsers?:string[];strictRoomMembership?:boolean;fetchImpl?:typeof fetch;}
interface Enrollment{userId:string;deviceId:string;fingerprint:string;homeserver:string;}
export class MatrixBotClientAdapter implements MatrixClientAdapter{
 private readonly token:string;private readonly fetchImpl:typeof fetch;private machine?:OlmMachine;private handler?: (event:MatrixInbound)=>Promise<void>;private running=false;private loop?:Promise<void>;private readonly encryptedRooms=new Set<string>();private readonly roomMembers=new Map<string,string[]>();private readonly healthHandlers=new Set<(healthy:boolean,detail?:string)=>void>();private since?:string;
 constructor(private readonly options:MatrixClientOptions){ensurePrivateDirectory(options.storageDir);if(!existsSync(join(options.storageDir,"enrollment.json")))throw new Error("Matrix enrollment marker is missing; refusing to create a fresh device");this.token=readSecretFile(options.accessTokenFile,"Matrix access token");this.fetchImpl=options.fetchImpl??fetch;const syncFile=join(options.storageDir,"sync-token");if(existsSync(syncFile))this.since=readSecretFile(syncFile,"Matrix sync token")||undefined;}
 async start(handler:(event:MatrixInbound)=>Promise<void>):Promise<void>{if(this.running)return;this.handler=handler;const enrollment=this.readEnrollment();if(new URL(this.options.homeserver).protocol!=="https:")throw new Error("Matrix homeserver must use HTTPS");if(enrollment.homeserver.replace(/\/+$/,"")!==this.options.homeserver.replace(/\/+$/,""))throw new Error("Matrix homeserver differs from enrollment");const who=await this.request("GET","/_matrix/client/v3/account/whoami") as any;if(who.user_id!==this.options.userId||enrollment.userId!==who.user_id||enrollment.deviceId!==who.device_id)throw new Error("Matrix account/device identity differs from enrollment");const passphrase=readSecretFile(join(this.options.storageDir,"crypto-store.key"),"Matrix crypto store key");this.machine=await OlmMachine.initialize(new UserId(who.user_id),new DeviceId(who.device_id),join(this.options.storageDir,"crypto"),passphrase,StoreType.Sqlite);if(this.machine.identityKeys.ed25519.toBase64()!==enrollment.fingerprint)throw new Error("Matrix fingerprint differs from enrollment");
  for(const roomId of this.options.allowedRooms){await this.refreshRoom(roomId);if(!this.encryptedRooms.has(roomId))throw new Error(`Allowlisted Matrix room is not encrypted: ${roomId}`);}await this.flushCrypto();if(!this.since){const baseline=await this.request("GET","/_matrix/client/v3/sync?timeout=0") as any;await this.processSync(baseline,false);this.since=baseline.next_batch;this.persistSyncToken();}this.running=true;this.loop=this.syncLoop();this.reportHealth(true);}
 onHealth(handler:(healthy:boolean,detail?:string)=>void){this.healthHandlers.add(handler);return()=>this.healthHandlers.delete(handler);}
 async stop():Promise<void>{this.running=false;await Promise.race([this.loop??Promise.resolve(),new Promise<void>(r=>setTimeout(r,35_000))]);this.machine?.close();this.machine=undefined;}
 async sendEncrypted(roomId:string,threadId:string|undefined,text:string,transactionId:string,notice=false):Promise<string>{const machine=this.requiredMachine();if(!this.encryptedRooms.has(roomId))throw new Error("Refusing delivery to an unencrypted room");await this.refreshMembers(roomId);const memberIds=this.roomMembers.get(roomId)??[];const allowed=new Set([this.options.userId,...(this.options.allowedUsers??[])]);if(this.options.strictRoomMembership!==false&&memberIds.some(id=>!allowed.has(id)))throw new Error("unexpected_room_member");const users=memberIds.filter(id=>allowed.has(id)).map(id=>new UserId(id));await machine.updateTrackedUsers(users);const missing=await machine.getMissingSessions(users);if(missing)await this.sendCryptoRequest(missing);const settings=createEncryptionSettings(this.options.requireVerifiedDevices);for(const request of await machine.shareRoomKey(new RoomId(roomId),users,settings))await this.sendCryptoRequest(request);const content=threadId?threadMessageContent(text,threadId):{msgtype:notice?"m.notice":"m.text",body:text};if(notice)content.msgtype="m.notice";const encrypted=JSON.parse(await machine.encryptRoomEvent(new RoomId(roomId),"m.room.message",JSON.stringify(content)));const response=await this.request("PUT",`/_matrix/client/v3/rooms/${encodeURIComponent(roomId)}/send/m.room.encrypted/${encodeURIComponent(transactionId)}`,encrypted) as any;if(typeof response.event_id!=="string")throw new Error("Matrix homeserver did not acknowledge event");return response.event_id;}
 async isRoomEncrypted(roomId:string){if(!this.encryptedRooms.has(roomId))await this.refreshRoom(roomId);return this.encryptedRooms.has(roomId);}
 async members(roomId:string){if(!this.roomMembers.has(roomId))await this.refreshMembers(roomId);return[...(this.roomMembers.get(roomId)??[])];}
 async identity(){const enrollment=this.readEnrollment();return{userId:enrollment.userId,deviceId:enrollment.deviceId,fingerprint:enrollment.fingerprint};}
 async trustReport(roomId:string){const machine=this.requiredMachine();await this.refreshMembers(roomId);const members=this.roomMembers.get(roomId)??[];await machine.updateTrackedUsers(members.map(id=>new UserId(id)));await this.flushCrypto();const response=await this.request("POST","/_matrix/client/v3/keys/query",{device_keys:Object.fromEntries(members.map(id=>[id,[]]))}) as any;let total=0,trusted=0;const enrollment=this.readEnrollment();for(const[userId,devices]of Object.entries(response.device_keys??{}) as Array<[string,Record<string,unknown>]>){for(const deviceId of Object.keys(devices)){total++;const device=await machine.getDevice(new UserId(userId),new DeviceId(deviceId));if((userId===this.options.userId&&deviceId===enrollment.deviceId)||device?.isCrossSignedByOwner())trusted++;}}return{total,trusted};}
 private async syncLoop(){while(this.running){try{const query=new URLSearchParams({timeout:"30000"});if(this.since)query.set("since",this.since);const sync=await this.request("GET",`/_matrix/client/v3/sync?${query}`) as any;await this.processSync(sync);this.since=sync.next_batch;this.persistSyncToken();this.reportHealth(true);}catch(error){if(!this.running)return;this.reportHealth(false,error instanceof MatrixHttpError?`matrix_http_${error.status}`:"matrix_sync_failed");const delay=retryDelay(error);await new Promise(r=>setTimeout(r,delay));}}}
 private async processSync(sync:any,dispatch=true){const machine=this.requiredMachine();const toDevice=sync.to_device?.events??[],changed=sync.device_lists?.changed??[],left=sync.device_lists?.left??[];await machine.receiveSyncChanges(JSON.stringify(toDevice),new DeviceLists(changed.map((u:string)=>new UserId(u)),left.map((u:string)=>new UserId(u))),sync.device_one_time_keys_count??{},sync.device_unused_fallback_key_types??[]);await this.flushCrypto();
  for(const[roomId,room]of Object.entries(sync.rooms?.join??{}).slice(0,100) as Array<[string,any]>){for(const event of (room.state?.events??[]).slice(0,1000))await this.observeState(roomId,event);const routeTimeline=shouldRouteTimeline(dispatch,Boolean(room.timeline?.limited));for(const event of (room.timeline?.events??[]).slice(0,1000)){await this.observeState(roomId,event);if(event.type!=="m.room.encrypted")continue;try{const decrypted=await machine.decryptRoomEvent(JSON.stringify(event),new RoomId(roomId));const clear=JSON.parse(decrypted.event);if(clear.type!=="m.room.message"||!routeTimeline)continue;const shield=decrypted.shieldState(true);const senderId=decrypted.sender?.toString()??"";if(!senderId)continue;const senderDevice=decrypted.senderDevice;const device=senderDevice?await machine.getDevice(new UserId(senderId),senderDevice):null;const trusted=Boolean(device&&device.isCrossSignedByOwner()&&shield?.color!==ShieldColor.Red);await this.handler?.({roomId,eventId:String(event.event_id),senderId,timestamp:Number(event.origin_server_ts??Date.now()),content:clear.content??{},trusted});}catch{/* Fail closed: undecryptable events are never emitted. */}}}await this.flushCrypto();}
 private async observeState(roomId:string,event:any){if(event.type==="m.room.encryption"&&event.state_key==="")this.encryptedRooms.add(roomId);if(event.type==="m.room.member"&&typeof event.state_key==="string"){const members=new Set(this.roomMembers.get(roomId)??[]);if(event.content?.membership==="join")members.add(event.state_key);else members.delete(event.state_key);this.roomMembers.set(roomId,[...members]);if(this.machine&&event.content?.membership==="join")await this.machine.updateTrackedUsers([new UserId(event.state_key)]);}}
 private async refreshRoom(roomId:string){try{const encryption=await this.request("GET",`/_matrix/client/v3/rooms/${encodeURIComponent(roomId)}/state/m.room.encryption/` ) as any;if(encryption?.algorithm==="m.megolm.v1.aes-sha2")this.encryptedRooms.add(roomId);}catch(error){if((error as MatrixHttpError).status!==404)throw error;}await this.refreshMembers(roomId);}
 private async refreshMembers(roomId:string){const response=await this.request("GET",`/_matrix/client/v3/rooms/${encodeURIComponent(roomId)}/joined_members`) as any;const members=Object.keys(response.joined??{});this.roomMembers.set(roomId,members);if(this.machine)await this.machine.updateTrackedUsers(members.map(id=>new UserId(id)));}
 private async flushCrypto(){const machine=this.requiredMachine();for(let round=0;round<10;round++){const requests=await machine.outgoingRequests();if(!requests.length)return;for(const request of requests)await this.sendCryptoRequest(request);}throw new Error("Matrix crypto outgoing queue did not settle");}
 private async sendCryptoRequest(request:any){const map:Record<number,{method:"POST"|"PUT";path:string}>={
  [RequestType.KeysUpload]:{method:"POST",path:"/_matrix/client/v3/keys/upload"},[RequestType.KeysQuery]:{method:"POST",path:"/_matrix/client/v3/keys/query"},[RequestType.KeysClaim]:{method:"POST",path:"/_matrix/client/v3/keys/claim"},[RequestType.SignatureUpload]:{method:"POST",path:"/_matrix/client/v3/keys/signatures/upload"},
 };
 let target=map[request.type];if(request.type===RequestType.ToDevice)target={method:"PUT",path:`/_matrix/client/v3/sendToDevice/${encodeURIComponent(request.eventType)}/${encodeURIComponent(request.txnId)}`};if(request.type===RequestType.RoomMessage)target={method:"PUT",path:`/_matrix/client/v3/rooms/${encodeURIComponent(request.roomId)}/send/${encodeURIComponent(request.eventType)}/${encodeURIComponent(request.txnId)}`};if(!target)throw new Error(`Unsupported crypto request type ${request.type}`);const response=await this.request(target.method,target.path,JSON.parse(request.body));await this.requiredMachine().markRequestAsSent(request.id,request.type,JSON.stringify(response));}
 private async request(method:"GET"|"POST"|"PUT",path:string,body?:unknown):Promise<unknown>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),35_000);let response:Response;try{response=await this.fetchImpl(`${this.options.homeserver.replace(/\/+$/,"")}${path}`,{method,signal:controller.signal,headers:{authorization:`Bearer ${this.token}`,...(body!==undefined?{"content-type":"application/json"}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});}catch(error){clearTimeout(timer);throw error;}const declared=Number(response.headers.get("content-length")??0);if(declared>10_000_000)throw new Error("Matrix response exceeds size limit");const text=await readLimitedBody(response,10_000_000,controller);clearTimeout(timer);let value:any={};try{value=text?JSON.parse(text):{};}catch{}if(!response.ok)throw new MatrixHttpError(response.status,value?.errcode??"M_UNKNOWN",value?.error??text,value?.retry_after_ms);return value;}
 private persistSyncToken(){const path=join(this.options.storageDir,"sync-token");writeFileSync(path,`${this.since}\n`,{mode:0o600});chmodSync(path,0o600);}
 private reportHealth(healthy:boolean,detail?:string){for(const handler of this.healthHandlers)handler(healthy,detail);}
 private readEnrollment():Enrollment{return JSON.parse(readSecretFile(join(this.options.storageDir,"enrollment.json"),"Matrix enrollment marker")) as Enrollment;}
 private requiredMachine(){if(!this.machine)throw new Error("Matrix crypto is unavailable");return this.machine;}
}
async function readLimitedBody(response:Response,maximum:number,controller:AbortController):Promise<string>{if(!response.body)return"";const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;try{while(true){const{done,value}=await reader.read();if(done)break;if(value){size+=value.byteLength;if(size>maximum){controller.abort();throw new Error("Matrix response exceeds size limit");}chunks.push(value);}}}finally{reader.releaseLock();}return Buffer.concat(chunks.map(chunk=>Buffer.from(chunk))).toString("utf8");}
export class MatrixHttpError extends Error{constructor(readonly status:number,readonly code:string,message:string,readonly retryAfterMs?:number){super(message);}}
export function createEncryptionSettings(requireVerifiedDevices:boolean){const settings=new EncryptionSettings();if(requireVerifiedDevices)settings.sharingStrategy=CollectStrategy.IdentityBasedStrategy;settings.rotationPeriodMessages=1n;return settings;}
export function shouldRouteTimeline(afterBaseline:boolean,limited:boolean){return afterBaseline&&!limited;}
function retryDelay(error:unknown){const value=(error as MatrixHttpError).retryAfterMs;return typeof value==="number"?Math.max(100,value):5000;}
