import { chmodSync, existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { createServer } from "node:http";
import { join, resolve } from "node:path";
import { verifyNativeCryptoIntegrity } from "../src/native-integrity.ts";
verifyNativeCryptoIntegrity();
const {DeviceId,OlmMachine,RequestType,StoreType,UserId}=await import("@matrix-org/matrix-sdk-crypto-nodejs");
import { ensurePrivateDirectory, resolvePaths } from "../src/paths.ts";
const {MatrixBotClientAdapter}=await import("../src/matrix/matrix-client.ts");
const args=parse(process.argv.slice(2));const homeserver=required(args,"homeserver").replace(/\/+$/,"");if(new URL(homeserver).protocol!=="https:")throw new Error("Matrix homeserver must use HTTPS");const expectedUser=required(args,"user-id"),deviceName=args.get("device-name")??"pi-ng gateway";const dir=resolve(args.get("storage-dir")??resolvePaths().matrixDir);ensurePrivateDirectory(dir);const marker=join(dir,"enrollment.json");if(existsSync(marker)&&!args.has("force"))throw new Error("An enrollment already exists. Use --force only for intentional device replacement.");if(args.has("force")){rmSync(join(dir,"crypto"),{recursive:true,force:true});rmSync(marker,{force:true});}
let token:string,deviceId:string,userId:string;if(args.get("token-file")){token=readFileSync(resolve(args.get("token-file")!),"utf8").trim();const who=await request("GET","/_matrix/client/v3/account/whoami",undefined,token) as any;userId=who.user_id;deviceId=who.device_id;const keys=await request("POST","/_matrix/client/v3/keys/query",{device_keys:{[userId]:[deviceId]}},token) as any;if(keys.device_keys?.[userId]?.[deviceId])throw new Error("Imported token belongs to a device that already has E2EE keys. Restore its original crypto store or create a fresh pi-ng device with password login.");}else if(args.has("password-stdin")){const password=readFileSync(0,"utf8").trim();if(!password)throw new Error("No password received on stdin");const login=await request("POST","/_matrix/client/v3/login",{type:"m.login.password",identifier:{type:"m.id.user",user:expectedUser},password,initial_device_display_name:deviceName}) as any;token=login.access_token;deviceId=login.device_id;userId=login.user_id;}else if(args.has("sso")){const loginToken=await receiveSsoLoginToken(homeserver);const login=await request("POST","/_matrix/client/v3/login",{type:"m.login.token",token:loginToken,initial_device_display_name:deviceName}) as any;token=login.access_token;deviceId=login.device_id;userId=login.user_id;}else throw new Error("Use --sso, --token-file PATH, or pipe a password with --password-stdin");if(userId!==expectedUser)throw new Error(`Credential belongs to ${userId}, not ${expectedUser}`);if(!token||!deviceId)throw new Error("Homeserver did not return token/device identity");
const tokenFile=resolve(args.get("output-token-file")??join(dir,"access-token"));writeFileSync(tokenFile,`${token}\n`,{mode:0o600});chmodSync(tokenFile,0o600);const keyFile=join(dir,"crypto-store.key");if(!existsSync(keyFile))writeFileSync(keyFile,randomBytes(32).toString("base64url"),{mode:0o600});chmodSync(keyFile,0o600);const passphrase=readFileSync(keyFile,"utf8").trim();const machine=await OlmMachine.initialize(new UserId(userId),new DeviceId(deviceId),join(dir,"crypto"),passphrase,StoreType.Sqlite);for(const outgoing of await machine.outgoingRequests()){const target=requestTarget(outgoing as any);const response=await request(target.method,target.path,JSON.parse((outgoing as any).body),token);await machine.markRequestAsSent((outgoing as any).id,(outgoing as any).type,JSON.stringify(response));}const identity={version:1,userId,deviceId,fingerprint:machine.identityKeys.ed25519.toBase64(),homeserver,createdAt:new Date().toISOString()};machine.close();writeFileSync(marker,JSON.stringify(identity,null,2),{mode:0o600});chmodSync(marker,0o600);
const testRoom=args.get("test-room");if(testRoom){const adapter=new MatrixBotClientAdapter({homeserver,userId,accessTokenFile:tokenFile,storageDir:dir,requireVerifiedDevices:false,allowedRooms:[testRoom],strictRoomMembership:false});let received=false;await adapter.start(async event=>{if(event.content.body==="pi-ng encrypted enrollment test")received=true;});await adapter.sendEncrypted(testRoom,undefined,"pi-ng encrypted enrollment test",`enroll-${crypto.randomUUID()}`,true);const deadline=Date.now()+20_000;while(!received&&Date.now()<deadline)await new Promise(r=>setTimeout(r,100));await adapter.stop();if(!received)throw new Error("Encrypted test event was sent but not received/decrypted before timeout");}
console.log(`Enrolled ${identity.userId}`);console.log(`Device ID: ${identity.deviceId}`);console.log(`Ed25519 fingerprint: ${identity.fingerprint}`);console.log(`Token file: ${tokenFile}`);console.log("Verify this device and fingerprint from Element before enabling routing. Then run: npm run doctor -- --online");
async function request(method:"GET"|"POST"|"PUT",path:string,body?:unknown,accessToken?:string){const response=await fetch(`${homeserver}${path}`,{method,headers:{...(accessToken?{authorization:`Bearer ${accessToken}`}:{ }),...(body?{"content-type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await response.text();const value=text?JSON.parse(text):{};if(!response.ok)throw new Error(`Matrix ${response.status}: ${value.error??value.errcode??text}`);return value;}
function requestTarget(value:any):{method:"POST"|"PUT";path:string}{if(value.type===RequestType.KeysUpload)return{method:"POST",path:"/_matrix/client/v3/keys/upload"};if(value.type===RequestType.KeysQuery)return{method:"POST",path:"/_matrix/client/v3/keys/query"};if(value.type===RequestType.KeysClaim)return{method:"POST",path:"/_matrix/client/v3/keys/claim"};if(value.type===RequestType.SignatureUpload)return{method:"POST",path:"/_matrix/client/v3/keys/signatures/upload"};if(value.type===RequestType.ToDevice)return{method:"PUT",path:`/_matrix/client/v3/sendToDevice/${encodeURIComponent(value.eventType)}/${encodeURIComponent(value.txnId)}`};throw new Error(`Unsupported enrollment crypto request ${value.type}`);}
async function receiveSsoLoginToken(baseUrl:string):Promise<string>{let settle:(value:string)=>void,reject:(error:Error)=>void;const result=new Promise<string>((resolve,fail)=>{settle=resolve;reject=fail;});const server=createServer((request,response)=>{try{const url=new URL(request.url??"/","http://127.0.0.1");const token=url.searchParams.get("loginToken");if(!token){response.writeHead(400,{"content-type":"text/plain"});response.end("Matrix login did not return a login token. You can close this window.");return;}response.writeHead(200,{"content-type":"text/plain"});response.end("pi-ng Matrix login completed. You can close this window.");settle(token);}catch(error){reject(error instanceof Error?error:new Error(String(error)));}finally{server.close();}});await new Promise<void>((resolve,fail)=>{server.once("error",fail);server.listen(0,"127.0.0.1",()=>resolve());});const address=server.address();if(!address||typeof address==="string"){server.close();throw new Error("Could not create the local SSO callback");}const callback=`http://127.0.0.1:${address.port}/callback`;const redirect=new URL("/_matrix/client/v3/login/sso/redirect",baseUrl);redirect.searchParams.set("redirectUrl",callback);console.log("Open this URL in a browser and complete the GitHub/SSO login:");console.log(redirect.toString());const timeout=setTimeout(()=>{server.close();reject(new Error("Matrix SSO login timed out"));},5*60_000);try{return await result;}finally{clearTimeout(timeout);server.close();}}
function parse(values:string[]){const flags=new Set(["password-stdin","sso","force"]);const out=new Map<string,string>();for(let i=0;i<values.length;i++){const value=values[i]!;if(!value.startsWith("--"))continue;const key=value.slice(2);if(flags.has(key))out.set(key,"true");else{const next=values[++i];if(!next)throw new Error(`Missing value for ${value}`);out.set(key,next);}}return out;}function required(values:Map<string,string>,key:string){const value=values.get(key);if(!value)throw new Error(`--${key} is required`);return value;}
