import { createConnection, type Socket } from "node:net";
import { BROKER_CAPABILITIES, envelope, parseEnvelope, type BrokerSession, type PromptSubmit } from "./broker-protocol.ts";
export interface BrokerClientOptions{socketPath:string;authToken:string|(()=>string);reconnectMs?:number;maxMessageBytes?:number;}
export interface BrokerClient{connect():void;register(session:Omit<BrokerSession,"connectedAt"|"lastSeenAt">):void;update(update:Partial<Pick<BrokerSession,"name"|"model"|"status"|"cwd">>):void;unregister():void;respondStarted(requestId:string):void;respondCompleted(requestId:string,message:string):void;respondFailed(requestId:string,errorCode:string,message?:string):void;publishNotification(message:string,urgency?:"low"|"normal"|"high",compatibilitySignal?:boolean):Promise<void>;onPrompt(handler:(prompt:PromptSubmit)=>void|Promise<void>):()=>void;onCancel(handler:(requestId:string)=>void|Promise<void>):()=>void;dispose():void;}
export function createBrokerClient(options:BrokerClientOptions):BrokerClient{
 let socket:Socket|undefined,registration:Omit<BrokerSession,"connectedAt"|"lastSeenAt">|undefined,timer:ReturnType<typeof setTimeout>|undefined,disposed=false,connected=false;const prompts=new Set<(p:PromptSubmit)=>void|Promise<void>>(),cancels=new Set<(id:string)=>void|Promise<void>>(),acks=new Map<string,{resolve:()=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>}>();
 const send=(value:unknown)=>{if(connected&&socket?.writable)socket.write(`${JSON.stringify(value)}\n`);};
 const connect=()=>{if(disposed||socket)return;const next=createConnection(options.socketPath);socket=next;next.on("connect",()=>{connected=true;let authToken:string;try{authToken=typeof options.authToken==="function"?options.authToken():options.authToken;}catch{next.destroy();return;}send(envelope("hello",{clientName:"pi-extension",capabilities:BROKER_CAPABILITIES,authToken}));if(registration)send(envelope("session.register",registration));});read(next,options.maxMessageBytes??1_000_000,async value=>{let m;try{m=parseEnvelope(value);}catch{return;}if(m.operation==="prompt.submit"){for(const h of prompts)await h(m.payload as PromptSubmit);}else if(m.operation==="prompt.cancel"){for(const h of cancels)await h((m.payload as any).requestId);}else if(m.operation==="delivery.ack"&&m.correlationId){const a=acks.get(m.correlationId);if(a){clearTimeout(a.timer);acks.delete(m.correlationId);a.resolve();}}else if(m.operation==="error"&&m.correlationId){const a=acks.get(m.correlationId);if(a){clearTimeout(a.timer);acks.delete(m.correlationId);a.reject(new Error((m.payload as any).code??"broker_error"));}}});const down=()=>{if(socket!==next)return;socket=undefined;connected=false;if(!disposed&&!timer){timer=setTimeout(()=>{timer=undefined;connect()},options.reconnectMs??2000);timer.unref();}};next.on("close",down);next.on("error",down);};
 const withSession=(op:"prompt.started"|"prompt.completed"|"prompt.failed",payload:Record<string,unknown>)=>{if(registration)send(envelope(op,{...payload,sessionId:registration.sessionId}));};
 return{connect,register(value){registration={...value};connect();if(connected)send(envelope("session.register",registration));},update(value){if(registration)registration={...registration,...value};send(envelope("session.update",value));},unregister(){registration=undefined;send(envelope("session.unregister",{}));},respondStarted(id){withSession("prompt.started",{requestId:id});},respondCompleted(id,message){withSession("prompt.completed",{requestId:id,message});},respondFailed(id,errorCode,message){withSession("prompt.failed",{requestId:id,errorCode,...(message?{message}:{})});},publishNotification(message,urgency="normal",compatibilitySignal=false){connect();const m=envelope("notification.publish",{message,urgency,compatibilitySignal});return new Promise<void>((resolve,reject)=>{const t=setTimeout(()=>{acks.delete(m.messageId);reject(new Error("broker acknowledgement timeout"));},30_000);acks.set(m.messageId,{resolve,reject,timer:t});send(m);});},onPrompt(h){prompts.add(h);return()=>prompts.delete(h);},onCancel(h){cancels.add(h);return()=>cancels.delete(h);},dispose(){disposed=true;if(timer)clearTimeout(timer);for(const a of acks.values()){clearTimeout(a.timer);a.reject(new Error("disposed"));}acks.clear();socket?.destroy();socket=undefined;connected=false;}};
}
function read(socket:Socket,max:number,handler:(v:unknown)=>void|Promise<void>){let b="";socket.setEncoding("utf8");socket.on("data",(c:string)=>{b+=c;if(Buffer.byteLength(b)>max){socket.destroy();return;}for(let i;(i=b.indexOf("\n"))>=0;){const l=b.slice(0,i);b=b.slice(i+1);if(l.trim())try{void handler(JSON.parse(l));}catch{}}});}
