import { chmodSync, existsSync, lstatSync, rmSync } from "node:fs";
import { createConnection, createServer, type Server, type Socket } from "node:net";
import { timingSafeEqual } from "node:crypto";
import { dirname } from "node:path";
import { ensurePrivateDirectory } from "./paths.ts";
import { BROKER_CAPABILITIES, BROKER_PROTOCOL_VERSION, envelope, parseEnvelope, promptSubmitSchema, sessionRegistrationSchema, validatePayload, type BrokerEnvelope, type BrokerSession, type PromptResult, type PromptSubmit } from "./broker-protocol.ts";

export interface BrokerServerOptions { socketPath: string; authToken: string; maxMessageBytes?: number; maxQueueDepth?: number; requestTimeoutMs?: number; }
export interface BrokerServer {
 start():Promise<void>; stop():Promise<void>; listSessions():BrokerSession[]; submitPrompt(input:PromptSubmit):Promise<{accepted:boolean;reason?:string}>; cancel(requestId:string):boolean;
 onResult(handler:(operation:"prompt.started"|"prompt.completed"|"prompt.failed",result:PromptResult)=>void|Promise<void>):()=>void;
 onNotification(handler:(payload:{message:string;urgency:"low"|"normal"|"high";compatibilitySignal?:boolean})=>void|Promise<void>):()=>void;
}
type Entry={session:BrokerSession;socket:Socket;capabilities:Set<string>;queueDepth:number};
export function createBrokerServer(options:BrokerServerOptions):BrokerServer{
 const maxBytes=options.maxMessageBytes??1_000_000,maxQueue=options.maxQueueDepth??100,timeout=options.requestTimeoutMs??300_000;
 const sessions=new Map<string,Entry>(),sockets=new Set<Socket>(),authenticated=new WeakSet<Socket>(),pending=new Map<string,{sessionId:string,timer:ReturnType<typeof setTimeout>}>(),seen=new Set<string>();
 let notificationDepth=0;const results=new Set<(operation:"prompt.started"|"prompt.completed"|"prompt.failed",result:PromptResult)=>void|Promise<void>>(),notifications=new Set<(p:{message:string;urgency:"low"|"normal"|"high";compatibilitySignal?:boolean})=>void|Promise<void>>(); let server:Server|undefined;
 const remove=(socket:Socket)=>{for(const[id,e]of sessions)if(e.socket===socket){sessions.delete(id);for(const[request,p]of pending)if(p.sessionId===id){clearTimeout(p.timer);pending.delete(request);void emitResult("prompt.failed",{requestId:request,sessionId:id,errorCode:"session_disconnected"});}}};
 const emitResult=async(op:"prompt.started"|"prompt.completed"|"prompt.failed",result:PromptResult)=>{for(const h of results)await h(op,result);};
 const handle=async(socket:Socket,msg:unknown)=>{
  let m:BrokerEnvelope;try{m=parseEnvelope(msg);validatePayload(m);}catch(error){send(socket,envelope("error",{code:"invalid_message",message:error instanceof Error?error.message:"invalid"}));return;}
  if(m.operation==="hello"){const p=m.payload as any;if(!safeEqual(p.authToken,options.authToken)){send(socket,envelope("error",{code:"authentication_failed"},m.messageId));socket.destroy();return;}authenticated.add(socket);const caps=(p.capabilities as string[]).filter(c=>(BROKER_CAPABILITIES as readonly string[]).includes(c));(socket as any).piCapabilities=new Set(caps);send(socket,envelope("hello.ack",{protocolVersion:BROKER_PROTOCOL_VERSION,capabilities:BROKER_CAPABILITIES},m.messageId));return;}
  if(!authenticated.has(socket)){send(socket,envelope("error",{code:"hello_required"},m.messageId));return;}
  if(m.operation==="health.query"){send(socket,envelope("health.result",{status:"healthy",sessions:sessions.size,pending:pending.size},m.messageId));return;}
  if(m.operation==="session.register"){
   const negotiated=(socket as any).piCapabilities as Set<string>|undefined;if(!negotiated?.has("session.register")){send(socket,envelope("error",{code:"capability_not_negotiated"},m.messageId));return;}const value=sessionRegistrationSchema.parse(m.payload);const conflict=sessions.get(value.sessionId);if(conflict&&conflict.socket!==socket&&!conflict.socket.destroyed){send(socket,envelope("error",{code:"session_conflict"},m.messageId));return;}
   remove(socket);const now=Date.now();sessions.set(value.sessionId,{session:{...value,connectedAt:now,lastSeenAt:now},socket,capabilities:(socket as any).piCapabilities??new Set(),queueDepth:0});send(socket,envelope("delivery.ack",{accepted:true},m.messageId));return;
  }
  const own=[...sessions.values()].find(e=>e.socket===socket);
  if(m.operation==="session.update"&&own){own.session={...own.session,...m.payload as object,sessionId:own.session.sessionId,connectedAt:own.session.connectedAt,lastSeenAt:Date.now()};return;}
  if(m.operation==="session.unregister"){remove(socket);return;}
  if(m.operation==="session.list"){send(socket,envelope("session.list.result",{sessions:[...sessions.values()].map(e=>e.session)},m.messageId));return;}
  if((m.operation==="prompt.started"||m.operation==="prompt.completed"||m.operation==="prompt.failed")&&own){const p=m.payload as PromptResult;const active=pending.get(p.requestId);if(p.sessionId!==own.session.sessionId||!active||active.sessionId!==own.session.sessionId){send(socket,envelope("error",{code:"request_not_owned"},m.messageId));return;}if(m.operation!=="prompt.started"){clearTimeout(active.timer);pending.delete(p.requestId);own.queueDepth=Math.max(0,own.queueDepth-1);}await emitResult(m.operation,p);send(socket,envelope("delivery.ack",{accepted:true},m.messageId));return;}
  if(m.operation==="notification.publish"){if(!own?.capabilities.has("notification.publish")){send(socket,envelope("error",{code:"capability_not_negotiated"},m.messageId));return;}if(notificationDepth>=maxQueue){send(socket,envelope("error",{code:"queue_full"},m.messageId));return;}notificationDepth++;try{for(const h of notifications)await h(m.payload as any);send(socket,envelope("delivery.ack",{accepted:true},m.messageId));}finally{notificationDepth--;}}
 };
 return {async start(){if(server)return;ensurePrivateDirectory(dirname(options.socketPath));if(existsSync(options.socketPath)){const st=lstatSync(options.socketPath);if(st.isSymbolicLink()||!st.isSocket())throw new Error("Unsafe broker socket path");if(await canConnect(options.socketPath))throw new Error("Broker already running");rmSync(options.socketPath,{force:true});}server=createServer(socket=>{sockets.add(socket);readLines(socket,maxBytes,v=>handle(socket,v));socket.on("close",()=>{sockets.delete(socket);remove(socket)});socket.on("error",()=>remove(socket));});await new Promise<void>((resolve,reject)=>{server!.once("error",reject);server!.listen(options.socketPath,()=>resolve());});chmodSync(options.socketPath,0o600);},async stop(){const active=server;server=undefined;for(const p of pending.values())clearTimeout(p.timer);pending.clear();for(const s of sockets)s.destroy();sockets.clear();sessions.clear();if(active)await new Promise<void>(r=>active.close(()=>r()));rmSync(options.socketPath,{force:true});},listSessions(){return[...sessions.values()].map(e=>({...e.session}));},async submitPrompt(input){promptSubmitSchema.parse(input);if(seen.has(input.requestId)||pending.has(input.requestId))return{accepted:false,reason:"duplicate_request"};const entry=input.sessionId?sessions.get(input.sessionId):[...sessions.values()].find(e=>e.session.agentId===input.agentId);if(entry?.session.agentId!==input.agentId)return{accepted:false,reason:"agent_mismatch"};if(!entry||!entry.socket.writable)return{accepted:false,reason:"no_session"};if(entry.queueDepth>=maxQueue)return{accepted:false,reason:"queue_full"};seen.add(input.requestId);if(seen.size>10_000)seen.delete(seen.values().next().value!);entry.queueDepth++;const timer=setTimeout(()=>{pending.delete(input.requestId);entry.queueDepth=Math.max(0,entry.queueDepth-1);void emitResult("prompt.failed",{requestId:input.requestId,sessionId:entry.session.sessionId,errorCode:"timeout"});},timeout);timer.unref();pending.set(input.requestId,{sessionId:entry.session.sessionId,timer});send(entry.socket,envelope("prompt.submit",input));return{accepted:true};},cancel(requestId){const active=pending.get(requestId);const entry=active?sessions.get(active.sessionId):undefined;if(!entry)return false;send(entry.socket,envelope("prompt.cancel",{requestId}));return true;},onResult(h){results.add(h);return()=>results.delete(h);},onNotification(h){notifications.add(h);return()=>notifications.delete(h);}};
}
function send(socket:Socket,value:unknown){if(socket.writable)socket.write(`${JSON.stringify(value)}\n`);}
function readLines(socket:Socket,max:number,handler:(v:unknown)=>void|Promise<void>){let b="";socket.setEncoding("utf8");socket.on("data",(c:string)=>{b+=c;if(Buffer.byteLength(b)>max){socket.destroy(new Error("message_too_large"));return;}for(let i;(i=b.indexOf("\n"))>=0;){const l=b.slice(0,i);b=b.slice(i+1);if(l.trim())try{void Promise.resolve(handler(JSON.parse(l))).catch(()=>undefined);}catch{send(socket,envelope("error",{code:"malformed_json"}));}}});}
function safeEqual(left:string,right:string){const a=Buffer.from(left),b=Buffer.from(right);return a.length===b.length&&timingSafeEqual(a,b);}
async function canConnect(path:string){return new Promise<boolean>(resolve=>{const s=createConnection(path);const t=setTimeout(()=>{s.destroy();resolve(false)},300);s.once("connect",()=>{clearTimeout(t);s.destroy();resolve(true)});s.once("error",()=>{clearTimeout(t);resolve(false)});});}
