import type { PiNgConfig } from "./config.ts";
import { AgentProfiles } from "./agent-profiles.ts";
import { AgentManager } from "./agent-manager.ts";
import type { BrokerServer } from "./broker-server.ts";
import { createBrokerServer } from "./broker-server.ts";
import { DeliveryManager } from "./delivery-manager.ts";
import type { Logger } from "./logger.ts";
import { JsonLogger } from "./logger.ts";
import { Metrics } from "./metrics.ts";
import type { PiNgPaths } from "./paths.ts";
import { ensurePrivateDirectory, resolvePaths } from "./paths.ts";
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { getAgentDir } from "@earendil-works/pi-coding-agent";
import { randomBytes } from "node:crypto";
import { readSecretFile } from "./secrets.ts";
import { SignalTransport } from "./signal-transport.ts";
import { SqliteStateStore } from "./sqlite-state-store.ts";
import type { Conversation, StateStore } from "./state-store.ts";
import type { ChatEvent, ChatTransport } from "./transport.ts";
import { DisabledTransport } from "./transport.ts";
import { MatrixBotClientAdapter } from "./matrix/matrix-client.ts";
import { authorizeMatrixEvent } from "./matrix/matrix-crypto-policy.ts";
import { parsePiCommand, type PiCommand } from "./matrix/matrix-event-router.ts";
import { MatrixTransport } from "./matrix/matrix-transport.ts";

export interface DaemonDependencies {paths?:PiNgPaths;store?:StateStore;broker?:BrokerServer;transports?:ChatTransport[];logger?:Logger;}
export class PiNgDaemon{
 private readonly paths:PiNgPaths;private readonly store:StateStore;private readonly broker:BrokerServer;private readonly transports=new Map<string,ChatTransport>();private readonly logger:Logger;private readonly metrics=new Metrics();private readonly profiles:AgentProfiles;private readonly agents:AgentManager;private readonly delivery:DeliveryManager;private readonly tails=new Map<string,Promise<void>>();private readonly limits=new SlidingLimits();private unsubscribers:(()=>void)[]=[];private started=false;private signalConversationRoot?:string;
 constructor(private readonly config:PiNgConfig,deps:DaemonDependencies={}){
  this.paths=deps.paths??resolvePaths();ensurePrivateDirectory(this.paths.runtimeDir);const brokerAuthToken=brokerToken(this.paths.brokerKeyFile);this.store=deps.store??new SqliteStateStore(this.paths.databaseFile);this.broker=deps.broker??createBrokerServer({socketPath:this.paths.brokerSocket,authToken:brokerAuthToken,...config.broker});this.logger=deps.logger??new JsonLogger();this.profiles=new AgentProfiles(config.agents);this.agents=new AgentManager(this.profiles,this.broker,managedAuthFile(this.paths.dataDir));
  const supplied=deps.transports??this.createTransports();for(const transport of supplied)this.transports.set(transport.kind,transport);
  this.delivery=new DeliveryManager({store:this.store,transports:this.transports,spoolKeyFile:this.paths.spoolKeyFile,...config.delivery,onDeadLetter:id=>this.logger.log("error","delivery.dead_letter",{deliveryId:id})});
 }
 async start():Promise<void>{if(this.started)return;this.started=true;this.store.migrate();const orphaned=this.store.markUncertainRequestsOrphaned();for(const binding of this.store.listSessions())this.store.updateSessionStatus(binding.piSessionId,"disconnected");await this.broker.start();this.unsubscribers.push(this.broker.onNotification(p=>this.handleNotification(p)));
  for(const transport of this.transports.values()){this.unsubscribers.push(transport.onEvent(e=>this.handleEvent(e)));await transport.start();}
  this.delivery.start();this.logger.log("info","daemon.started",{orphaned,transports:[...this.transports.keys()]});}
 async stop():Promise<void>{if(!this.started)return;this.started=false;this.delivery.stop();for(const unsub of this.unsubscribers)unsub();this.unsubscribers=[];for(const transport of this.transports.values())await transport.stop();this.agents.dispose();await this.broker.stop();this.store.close();this.logger.log("info","daemon.stopped");}
 health(){return{started:this.started,transports:Object.fromEntries([...this.transports].map(([k,v])=>[k,v.health()])),sessions:this.broker.listSessions().length,metrics:this.metrics.snapshot(),deadLetters:this.store.listDeliveries("dead_letter").length};}
 private createTransports():ChatTransport[]{const values:ChatTransport[]=[];
  if(this.config.matrix.enabled){const adapter=new MatrixBotClientAdapter({homeserver:this.config.matrix.homeserver!,userId:this.config.matrix.userId!,accessTokenFile:this.config.matrix.accessTokenFile!,storageDir:this.paths.matrixDir,requireVerifiedDevices:this.config.matrix.requireVerifiedDevices,allowedRooms:this.config.matrix.allowedRooms,allowedUsers:this.config.matrix.allowedUsers,strictRoomMembership:this.config.matrix.strictRoomMembership});values.push(new MatrixTransport(adapter));}else values.push(new DisabledTransport("matrix"));
  if(this.config.signal.enabled&&this.config.signal.mode!=="disabled")values.push(new SignalTransport({restUrl:this.config.signal.restUrl,account:this.config.signal.account!,mode:this.config.signal.mode,pollIntervalMs:this.config.signal.pollIntervalMs}));else values.push(new DisabledTransport("signal"));return values;}
 private async handleEvent(event:ChatEvent):Promise<void>{try{
  if(this.store.hasInbound(event.transport,event.eventId)){this.metrics.increment("inbound.deduplicated");return;}
  if(event.transport==="matrix"){const matrix=this.transports.get("matrix");if(!(matrix instanceof MatrixTransport)||!event.roomId)return;const security=await matrix.roomSecurity(event.roomId);const decision=authorizeMatrixEvent(event,{...security,decrypted:event.encrypted,deviceTrusted:event.trusted},{botUserId:this.config.matrix.userId!,...this.config.matrix});if(!decision.allowed){this.store.recordInboundDecision("matrix",event.eventId);this.metrics.increment(`policy.refused.${decision.reason}`);this.logger.log("warn","matrix.policy_refused",{reason:decision.reason,roomId:event.roomId,senderId:event.senderId,eventId:event.eventId});return;}
   if(!this.limits.allow(`u:${event.senderId}`,this.config.matrix.maxRequestsPerUserPerMinute)||!this.limits.allow(`r:${event.roomId}`,this.config.matrix.maxRequestsPerRoomPerMinute)){this.store.recordInboundDecision("matrix",event.eventId);this.metrics.increment("rate_limited");await matrix.send({transport:"matrix",roomId:event.roomId,threadId:event.threadId},{text:"pi-ng rate limit reached. Try again shortly.",notice:true});return;}
   const command=parsePiCommand(event.text);if(command){if(this.config.matrix.shadowMode){this.store.recordInboundDecision("matrix",event.eventId);this.logger.log("info","matrix.shadow_command",{eventId:event.eventId,roomId:event.roomId,command:command.kind});return;}await this.handleCommand(event,command);return;}
  }else if(this.config.signal.mode==="legacy-command"){
   const match=event.text.match(/^\/pi(?:\s+(.*))?$/s);if(match){const body=match[1]?.trim()??"";if(body==="sessions"){await this.reply(event,this.broker.listSessions().map(s=>`${s.sessionId} ${s.status}`).join("\n")||"No attached sessions.");return;}const fresh=body.match(/^new(?:\s+([a-z0-9_-]+))?(?:\s+(.+))?$/s);if(fresh){this.signalConversationRoot=event.eventId;const agent=fresh[1]&&this.config.agents.some(a=>a.id===fresh[1])?fresh[1]:this.config.agents[0]?.id;const prompt=fresh[2]??(fresh[1]&&!this.config.agents.some(a=>a.id===fresh[1])?body.slice(4):"");if(!prompt){await this.reply(event,"Usage: /pi new [agent-id] <message>");return;}await this.submitPromptEvent({...event,threadId:this.signalConversationRoot},agent,prompt);return;}if(!body){await this.reply(event,"Usage: /pi new [agent-id] <message> or /pi <message>");return;}this.signalConversationRoot??=event.eventId;await this.submitPromptEvent({...event,threadId:this.signalConversationRoot},undefined,body);return;}
   if(this.signalConversationRoot)event={...event,threadId:this.signalConversationRoot};else return;
  }
  await this.submitPromptEvent(event);
 }catch(error){this.logger.log("error","inbound.failed",{eventId:event.eventId,error:error instanceof Error?error.message:String(error)});}}
 private async submitPromptEvent(event:ChatEvent,agentOverride?:string,promptOverride?:string):Promise<void>{
  const roomId=event.roomId??"note-to-self",root=event.threadId??event.eventId;let conversation=this.store.findConversation(event.transport,roomId,root);
  const agentId=agentOverride??(event.transport==="matrix"?this.config.matrix.roomAgents[roomId]:this.config.agents[0]?.id);if(!conversation){if(!agentId){await this.reply(event,"No approved agent profile is configured for this room.");return;}this.profiles.get(agentId);conversation=this.store.createConversation({conversationId:crypto.randomUUID(),transport:event.transport,roomId,threadRootEventId:root,agentId,status:"active"});}
  if(conversation.status!=="active"){await this.reply(event,"This conversation is closed.");return;}
  const requestId=crypto.randomUUID();const accepted=this.store.acceptInbound({transport:event.transport,eventId:event.eventId,conversationId:conversation.conversationId,requestId});if(!accepted.accepted)return;
  if(this.config.matrix.shadowMode&&event.transport==="matrix"){this.store.transitionRequest(requestId,"queued","expired","shadow_mode");this.logger.log("info","matrix.shadow_decision",{conversationId:conversation.conversationId,eventId:event.eventId,agentId:conversation.agentId});return;}
  const task=async()=>{if(!this.store.transitionRequest(requestId,"queued","accepted"))return;this.store.transitionRequest(requestId,"accepted","running");try{const result=await this.agents.submit(conversation!,requestId,promptOverride??event.text,{transport:event.transport,eventId:event.eventId});this.logger.log("info","agent.completed",{requestId,toolExecutions:result.toolExecutions??[],responseBytes:Buffer.byteLength(result.response)});this.store.updateConversation(conversation!.conversationId,{piSessionId:result.sessionId});this.store.bindSession({piSessionId:result.sessionId,agentId:conversation!.agentId,conversationId:conversation!.conversationId,connectionStatus:"connected",lastSeenAt:Date.now()});const queued=this.delivery.completeRequestAndEnqueue({requestId,transport:event.transport,destination:roomId,...(event.threadId?{threadId:event.threadId}:{}),text:`[${conversation!.agentId}] ${result.response}`});if(!queued)throw new Error("request_state_conflict");this.metrics.increment("requests.completed");if(event.transport==="matrix"&&this.config.signal.enabled&&this.config.signal.fallbackPolicy==="generic-status-only")void this.notifySignalCompletion(conversation!.agentId);}catch(error){const current=this.store.getRequest(requestId);if(current?.status==="cancellation_requested")this.store.transitionRequest(requestId,"cancellation_requested","cancelled","cancelled");else this.store.transitionRequest(requestId,["accepted","running"],"failed",errorCode(error));await this.reply(event,"Pi request failed. Check daemon diagnostics.");this.metrics.increment("requests.failed");}};
  const previous=this.tails.get(conversation.conversationId)??Promise.resolve();const next=previous.then(task,task).finally(()=>{if(this.tails.get(conversation!.conversationId)===next)this.tails.delete(conversation!.conversationId);});this.tails.set(conversation.conversationId,next);void next.catch(error=>this.logger.log("error","request.tail_failed",{error:errorCode(error)}));
 }
 private async handleCommand(event:ChatEvent,command:PiCommand):Promise<void>{const room=event.roomId!;const root=event.threadId??event.eventId;const conversation=this.store.findConversation("matrix",room,root);
  if(command.kind!=="new"&&!this.recordControlEvent(event))return;if(!isCommandAuthorized(command.kind,event.senderId,room,this.config.matrix.administrators,this.config.matrix.controlRooms)){await this.reply(event,"This command is restricted to administrators in a control room.");return;}
  if(command.kind==="help"){await this.reply(event,"Commands: !pi (or /pi) agents, sessions, status, new <agent> [prompt], attach <session>, detach, close, cancel, retry --confirm");return;}
  if(command.kind==="agents"){await this.reply(event,this.profiles.list().map(p=>`${p.id}: ${p.name} (${p.mode})`).join("\n")||"No agents configured.");return;}
  if(command.kind==="sessions"){const attached=this.broker.listSessions().map(s=>`${s.sessionId} ${s.name??""} ${s.status}`);const managed=this.agents.listManaged().map(s=>`${s.sessionId} ${s.agentId} ${s.streaming?"working":"idle"}`);await this.reply(event,[...attached,...managed].join("\n")||"No sessions.");return;}
  if(command.kind==="status"){await this.reply(event,JSON.stringify(this.health(),null,2));return;}
  if(command.kind==="new"){this.profiles.get(command.agentId);if(conversation){await this.reply(event,"A conversation already exists in this thread.");return;}const created=this.store.createConversation({conversationId:crypto.randomUUID(),transport:"matrix",roomId:room,threadRootEventId:root,agentId:command.agentId,status:"active"});if(command.prompt)await this.submitPromptEvent({...event,text:command.prompt},command.agentId,command.prompt);else{const requestId=crypto.randomUUID();if(this.store.acceptInbound({transport:"matrix",eventId:event.eventId,conversationId:created.conversationId,requestId}).accepted)this.store.transitionRequest(requestId,"queued","completed");await this.reply(event,`Created conversation for ${created.agentId}.`);}return;}
  if(!conversation){await this.reply(event,"No conversation exists in this thread.");return;}
  if(command.kind==="attach"){const profile=this.profiles.get(conversation.agentId);if(profile.mode!=="attached"){await this.reply(event,"This conversation does not use an attached profile.");return;}const sessions=this.broker.listSessions();const exact=sessions.find(s=>s.sessionId===command.sessionId);const matches=exact?[exact]:sessions.filter(s=>s.sessionId.startsWith(command.sessionId));if(matches.length!==1){await this.reply(event,matches.length?"Session selector is ambiguous.":"Attached session not found.");return;}const target=matches[0]!;if(target.agentId!==profile.id||target.cwd!==profile.cwd){await this.reply(event,"Session does not match the approved agent profile.");return;}this.store.updateConversation(conversation.conversationId,{piSessionId:target.sessionId});await this.reply(event,`Attached ${target.sessionId}.`);return;}
  if(command.kind==="detach"){this.store.updateConversation(conversation.conversationId,{piSessionId:null});await this.reply(event,"Detached session.");return;}
  if(command.kind==="close"){this.agents.close(conversation);this.store.updateConversation(conversation.conversationId,{status:"archived"});await this.reply(event,"Conversation closed.");return;}
  if(command.kind==="cancel"){const running=this.store.listRequests("running",conversation.conversationId)[0];if(!running||!this.store.transitionRequest(running.requestId,"running","cancellation_requested")){await this.reply(event,"Nothing cancellable is running.");return;}const cancelled=await this.agents.cancel(conversation,running.requestId);if(!cancelled)this.store.transitionRequest(running.requestId,"cancellation_requested","running");await this.reply(event,cancelled?"Cancellation requested.":"Nothing cancellable is running.");return;}
  if(command.kind==="retry"){await this.reply(event,command.confirmed?"Uncertain prompt bodies are intentionally not persisted. Resubmit the prompt explicitly to retry.":"Retrying uncertain work requires !pi retry --confirm.");}
 }
 private recordControlEvent(event:ChatEvent):boolean{const roomId=event.roomId!;const root=`${event.threadId??event.eventId}:control`;let conversation=this.store.findConversation("matrix",roomId,root);conversation??=this.store.createConversation({conversationId:crypto.randomUUID(),transport:"matrix",roomId,threadRootEventId:root,agentId:this.config.agents[0]?.id??"control",status:"active"});const requestId=crypto.randomUUID();const accepted=this.store.acceptInbound({transport:"matrix",eventId:event.eventId,conversationId:conversation.conversationId,requestId}).accepted;if(accepted)this.store.transitionRequest(requestId,"queued","completed");return accepted;}
 private async reply(event:ChatEvent,text:string){const transport=this.transports.get(event.transport);if(transport){const result=await transport.send({transport:event.transport,...(event.roomId?{roomId:event.roomId}:{}),...(event.threadId?{threadId:event.threadId}:{})},{text,notice:true});if(event.transport==="signal"&&result.eventId)this.store.recordInboundDecision("signal",result.eventId);}}
 private async notifySignalCompletion(agentId:string){try{await Promise.race([this.transports.get("signal")?.send({transport:"signal"},{text:`Agent ${agentId} completed a response in Matrix.`,notice:true}).then(result=>{if(result.eventId)this.store.recordInboundDecision("signal",result.eventId);})??Promise.resolve(),new Promise((_,reject)=>setTimeout(()=>reject(new Error("signal_timeout")),10_000))]);}catch{this.logger.log("warn","signal.fallback_failed");}}
 private async handleNotification(payload:{message:string;urgency:"low"|"normal"|"high";compatibilitySignal?:boolean}){const kind=payload.compatibilitySignal?"signal":this.config.primaryTransport;const transport=this.transports.get(kind);if(!transport||transport.health().status==="disabled")throw new Error(`${kind} notification transport is unavailable`);const destination=kind==="matrix"?this.config.matrix.allowedRooms[0]:undefined;if(kind==="matrix"&&!destination)throw new Error("No administrator notification room configured");const result=await transport.send({transport:kind,...(destination?{roomId:destination}:{})},{text:payload.message,notice:true});if(kind==="signal"&&result.eventId)this.store.recordInboundDecision("signal",result.eventId);}
}
export function isCommandAuthorized(kind:PiCommand["kind"],senderId:string,roomId:string,administrators:string[],controlRooms:string[]):boolean{const privileged=new Set(["sessions","status","attach","detach","retry"]);return !privileged.has(kind)||(administrators.includes(senderId)&&controlRooms.includes(roomId));}
function brokerToken(path:string):string{if(!existsSync(path))writeFileSync(path,randomBytes(32).toString("base64url"),{mode:0o600,flag:"wx"});return readSecretFile(path,"broker key");}
function managedAuthFile(dataDir:string):string{const target=join(dataDir,"pi-auth.json");if(!existsSync(target))writeFileSync(target,`${readSecretFile(join(getAgentDir(),"auth.json"),"Pi auth state")}\n`,{mode:0o600,flag:"wx"});else readSecretFile(target,"managed Pi auth state");return target;}
function errorCode(error:unknown):string{const value=error instanceof Error?error.message:"agent_failed";const known=["cancelled","timeout","queue_full","no_session","attached_session_required","request_state_conflict","agent_concurrency_timeout","session_disconnected"];return known.includes(value)?value:"agent_failed";}
class SlidingLimits{private readonly hits=new Map<string,number[]>();allow(key:string,maximum:number){const now=Date.now(),cut=now-60_000;const values=(this.hits.get(key)??[]).filter(v=>v>=cut);if(values.length>=maximum){this.hits.set(key,values);return false;}values.push(now);this.hits.set(key,values);return true;}}
